
Q1 - K-Nearest Neighbors (KNN) Classification

In [187]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

In [188]:
# Load Iris Dataset

iris = load_iris()

X = iris.data
y = iris.target

print("Feature Shape :", X.shape)
print("Target Shape :", y.shape)

Feature Shape : (150, 4)
Target Shape : (150,)

In [189]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42
)

print("X_train :", X_train.shape)
print("X_test :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test :", y_test.shape)

X_train : (100, 4)
X_test : (50, 4)
y_train : (100,)
y_test : (50,)

In [190]:
neighbors = [3, 5, 7, 11, 13, 15]

accuracy_list = []

for k in neighbors:

    model = KNeighborsClassifier(n_neighbors=k)

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    accuracy_list.append(accuracy)

    print(f"K = {k}  Accuracy = {accuracy:.4f}")

K = 3  Accuracy = 0.9800
K = 5  Accuracy = 0.9800
K = 7  Accuracy = 0.9800
K = 11  Accuracy = 1.0000
K = 13  Accuracy = 1.0000
K = 15  Accuracy = 1.0000

In [191]:
comparison = pd.DataFrame({
    "K Value": neighbors,
    "Accuracy": accuracy_list
})

comparison

   K Value  Accuracy
0        3      0.98
1        5      0.98
2        7      0.98
3       11      1.00
4       13      1.00
5       15      1.00

In [192]:
best_index = comparison["Accuracy"].idxmax()

print("Best K Value :", comparison.loc[best_index, "K Value"])
print("Best Accuracy :", comparison.loc[best_index, "Accuracy"])

Best K Value : 11
Best Accuracy : 1.0

Q2 - Support Vector Machine (SVM) Classification

In [193]:
from sklearn.svm import SVC

In [194]:
C_values = [1, 10, 20]
kernels = ["linear", "rbf"]

results = []

for c in C_values:
    for kernel in kernels:

        model = SVC(C=c, kernel=kernel, random_state=42)

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        accuracy = accuracy_score(y_test, y_pred)

        results.append([c, kernel, accuracy])

        print(f"C = {c}, Kernel = {kernel}, Accuracy = {accuracy}")

C = 1, Kernel = linear, Accuracy = 1.0
C = 1, Kernel = rbf, Accuracy = 1.0
C = 10, Kernel = linear, Accuracy = 1.0
C = 10, Kernel = rbf, Accuracy = 0.98
C = 20, Kernel = linear, Accuracy = 0.98
C = 20, Kernel = rbf, Accuracy = 1.0

In [195]:
comparison = pd.DataFrame(
    results,
    columns=["C Value", "Kernel", "Accuracy"]
)

comparison

   C Value  Kernel  Accuracy
0        1  linear      1.00
1        1     rbf      1.00
2       10  linear      1.00
3       10     rbf      0.98
4       20  linear      0.98
5       20     rbf      1.00

In [196]:
best = comparison.loc[comparison["Accuracy"].idxmax()]

print("Best C :", best["C Value"])
print("Best Kernel :", best["Kernel"])
print("Best Accuracy :", best["Accuracy"])

Best C : 1
Best Kernel : linear
Best Accuracy : 1.0

Q3 - Hyperparameter Tuning using GridSearchCV

In [197]:
from sklearn.model_selection import GridSearchCV

In [198]:
svm = SVC(random_state=42)

In [199]:
param_grid = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

In [200]:
grid = GridSearchCV(
    estimator=svm,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy"
)

grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(random_state=42),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [201]:
results = pd.DataFrame(grid.cv_results_)

results[["param_C", "param_kernel", "mean_test_score"]]

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.93
2       10       linear             0.93
3       10          rbf             0.94
4       20       linear             0.93
5       20          rbf             0.95

In [202]:
print("Best Parameters :", grid.best_params_)
print("Best Score :", grid.best_score_)

Best Parameters : {'C': 1, 'kernel': 'linear'}
Best Score : 0.95

Q4 - Hyperparameter Tuning using RandomizedSearchCV

In [203]:
from sklearn.model_selection import RandomizedSearchCV

In [204]:
svm = SVC(random_state=42)

In [205]:
param_grid = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

In [206]:
random_search = RandomizedSearchCV(
    estimator=svm,
    param_distributions=param_grid,
    n_iter=5,
    cv=5,
    scoring="accuracy",
    random_state=42
)

random_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(random_state=42), n_iter=5,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['linear', 'rbf']},
                   random_state=42, scoring='accuracy')

In [207]:
results = pd.DataFrame(random_search.cv_results_)

results[["param_C", "param_kernel", "mean_test_score"]]

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.93
2       20          rbf             0.95
3       10       linear             0.93
4       20       linear             0.93

In [208]:
print("Best Parameters :", random_search.best_params_)
print("Best Score :", random_search.best_score_)

Best Parameters : {'kernel': 'linear', 'C': 1}
Best Score : 0.95

In [209]:
print("Grid Search Best Parameters :", grid.best_params_)
print("Grid Search Best Score :", grid.best_score_)

print("\nRandom Search Best Parameters :", random_search.best_params_)
print("Random Search Best Score :", random_search.best_score_)

Grid Search Best Parameters : {'C': 1, 'kernel': 'linear'}
Grid Search Best Score : 0.95

Random Search Best Parameters : {'kernel': 'linear', 'C': 1}
Random Search Best Score : 0.95

Q5 - Random Forest Classification

In [210]:
from sklearn.ensemble import RandomForestClassifier

In [211]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

In [212]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [213]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [214]:
y_pred = rf.predict(X_test)

In [215]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Random Forest Accuracy :", accuracy)

Random Forest Accuracy : 0.9

Q6 - AdaBoost Classification

In [216]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [217]:
adaboost = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

adaboost.fit(X_train, y_train)

y_pred_ada = adaboost.predict(X_test)

ada_accuracy = accuracy_score(y_test, y_pred_ada)

print("AdaBoost Accuracy :", ada_accuracy)

AdaBoost Accuracy : 0.9333333333333333

In [218]:
gradient = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gradient.fit(X_train, y_train)

y_pred_gradient = gradient.predict(X_test)

gradient_accuracy = accuracy_score(y_test, y_pred_gradient)

print("Gradient Boosting Accuracy :", gradient_accuracy)

Gradient Boosting Accuracy : 0.9666666666666667

In [219]:
comparison = pd.DataFrame({
    "Model": ["AdaBoost", "Gradient Boosting"],
    "Accuracy": [ada_accuracy, gradient_accuracy]
})

comparison

               Model  Accuracy
0           AdaBoost  0.933333
1  Gradient Boosting  0.966667

Q7 - Gradient Boosting Classification

In [220]:
from xgboost import XGBClassifier

In [221]:
xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

In [222]:
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [223]:
y_pred_xgb = xgb.predict(X_test)

In [224]:
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print("XGBoost Accuracy :", xgb_accuracy)

XGBoost Accuracy : 0.9333333333333333

Q8 – Hyperparameter Tuning on Random Forest

Q8 — Hyperparameter Tuning on Random Forest

In [225]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [226]:
rf = RandomForestClassifier(random_state=42)

In [227]:
param_grid = {
    "n_estimators": [50, 100, 150],
    "max_depth": [3, 5, 7]
}

In [228]:
grid_rf = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy"
)

grid_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [3, 5, 7],
                         'n_estimators': [50, 100, 150]},
             scoring='accuracy')

In [229]:
results = pd.DataFrame(grid_rf.cv_results_)

results[
    [
        "param_n_estimators",
        "param_max_depth",
        "mean_test_score"
    ]
]

   param_n_estimators  param_max_depth  mean_test_score
0                  50                3         0.958333
1                 100                3         0.958333
2                 150                3         0.958333
3                  50                5         0.950000
4                 100                5         0.950000
5                 150                5         0.950000
6                  50                7         0.950000
7                 100                7         0.950000
8                 150                7         0.950000

In [230]:
print("Best Parameters :", grid_rf.best_params_)
print("Best Score :", grid_rf.best_score_)

Best Parameters : {'max_depth': 3, 'n_estimators': 50}
Best Score : 0.9583333333333334

Q9 - Complete Model Comparison

In [231]:
svm_best = grid.best_estimator_

svm_pred = svm_best.predict(X_test)

svm_accuracy = accuracy_score(y_test, svm_pred)

In [232]:
comparison = pd.DataFrame({
    "Model": [
        "SVM",
        "Random Forest",
        "AdaBoost",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy": [
        svm_accuracy,
        accuracy,
        ada_accuracy,
        gradient_accuracy,
        xgb_accuracy
    ]
})

comparison

               Model  Accuracy
0                SVM  0.966667
1      Random Forest  0.900000
2           AdaBoost  0.933333
3  Gradient Boosting  0.966667
4            XGBoost  0.933333

In [233]:
best = comparison.loc[comparison["Accuracy"].idxmax()]

print("Best Model :", best["Model"])
print("Accuracy :", best["Accuracy"])

Best Model : SVM
Accuracy : 0.9666666666666667

In [234]:
comparison = comparison.sort_values(
    by="Accuracy",
    ascending=False
)

comparison

               Model  Accuracy
0                SVM  0.966667
3  Gradient Boosting  0.966667
2           AdaBoost  0.933333
4            XGBoost  0.933333
1      Random Forest  0.900000

Q10. Mini Project – Full Pipeline

In [235]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import (
    RandomForestClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier
)
from xgboost import XGBClassifier

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import joblib

In [236]:
df = pd.read_csv("Bank Customer Churn Prediction.csv")

# Encode
le_country = LabelEncoder()
le_gender = LabelEncoder()

df["country"] = le_country.fit_transform(df["country"])
df["gender"] = le_gender.fit_transform(df["gender"])

# Now create X and y
X = df.drop(["customer_id", "churn"], axis=1)
y = df["churn"]

In [237]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [238]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [239]:
neighbors = [3, 5, 7, 11, 13, 15]

results = []

for k in neighbors:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)

    y_pred = knn.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)

    results.append([k, accuracy])

comparison = pd.DataFrame(results, columns=["K", "Accuracy"])

comparison

    K  Accuracy
0   3    0.8205
1   5    0.8350
2   7    0.8370
3  11    0.8365
4  13    0.8355
5  15    0.8350

In [240]:
best_knn = comparison.loc[comparison["Accuracy"].idxmax()]

print(best_knn)

K           7.000
Accuracy    0.837
Name: 2, dtype: float64

In [241]:
results = []

C = [1, 10, 20]
kernel = ["linear", "rbf"]

for c in C:
    for k in kernel:

        svm = SVC(C=c, kernel=k)

        svm.fit(X_train_scaled, y_train)

        y_pred = svm.predict(X_test_scaled)

        accuracy = accuracy_score(y_test, y_pred)

        results.append([c, k, accuracy])

comparison = pd.DataFrame(
    results,
    columns=["C", "Kernel", "Accuracy"]
)

comparison

    C  Kernel  Accuracy
0   1  linear    0.7965
1   1     rbf    0.8560
2  10  linear    0.7965
3  10     rbf    0.8545
4  20  linear    0.7965
5  20     rbf    0.8455

In [242]:
best_svm = comparison.loc[comparison["Accuracy"].idxmax()]

print(best_svm)

C               1
Kernel        rbf
Accuracy    0.856
Name: 1, dtype: object

In [243]:
param_grid = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

grid = GridSearchCV(
    estimator=SVC(),
    param_grid=param_grid,
    cv=5,
    scoring="accuracy"
)

grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [244]:
results = pd.DataFrame(grid.cv_results_)

results[
    [
        "param_C",
        "param_kernel",
        "mean_test_score"
    ]
]

   param_C param_kernel  mean_test_score
0        1       linear         0.796250
1        1          rbf         0.854875
2       10       linear         0.796250
3       10          rbf         0.851375
4       20       linear         0.796250
5       20          rbf         0.848500

In [245]:
print("Best Parameters :", grid.best_params_)
print("Best Score :", grid.best_score_)

Best Parameters : {'C': 1, 'kernel': 'rbf'}
Best Score : 0.854875

In [246]:
random_search = RandomizedSearchCV(
    estimator=SVC(),
    param_distributions=param_grid,
    n_iter=5,
    cv=5,
    scoring="accuracy",
    random_state=42
)

random_search.fit(X_train_scaled, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['linear', 'rbf']},
                   random_state=42, scoring='accuracy')

In [247]:
results = pd.DataFrame(random_search.cv_results_)

results[
    [
        "param_C",
        "param_kernel",
        "mean_test_score"
    ]
]

   param_C param_kernel  mean_test_score
0        1       linear         0.796250
1        1          rbf         0.854875
2       20          rbf         0.848500
3       10       linear         0.796250
4       20       linear         0.796250

In [248]:
print("Best Parameters :", random_search.best_params_)
print("Best Score :", random_search.best_score_)

Best Parameters : {'kernel': 'rbf', 'C': 1}
Best Score : 0.854875

In [249]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy :", rf_accuracy)

Random Forest Accuracy : 0.864

In [250]:
ada = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

ada.fit(X_train, y_train)

y_pred_ada = ada.predict(X_test)

ada_accuracy = accuracy_score(y_test, y_pred_ada)

print("AdaBoost Accuracy :", ada_accuracy)

AdaBoost Accuracy : 0.8535

In [251]:
gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

gb_accuracy = accuracy_score(y_test, y_pred_gb)

print("Gradient Boosting Accuracy :", gb_accuracy)

Gradient Boosting Accuracy : 0.8675

In [252]:
xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print("XGBoost Accuracy :", xgb_accuracy)

XGBoost Accuracy : 0.8645

In [253]:
svm_best = grid.best_estimator_

svm_best.fit(X_train_scaled, y_train)

svm_pred = svm_best.predict(X_test_scaled)

svm_accuracy = accuracy_score(y_test, svm_pred)

comparison = pd.DataFrame({
    "Model": [
        "SVM",
        "Random Forest",
        "AdaBoost",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy": [
        svm_accuracy,
        rf_accuracy,
        ada_accuracy,
        gb_accuracy,
        xgb_accuracy
    ]
})

comparison = comparison.sort_values(
    by="Accuracy",
    ascending=False
)

comparison

               Model  Accuracy
3  Gradient Boosting    0.8675
4            XGBoost    0.8645
1      Random Forest    0.8640
0                SVM    0.8560
2           AdaBoost    0.8535

In [254]:
best = comparison.loc[comparison["Accuracy"].idxmax()]

print(best)

Model       Gradient Boosting
Accuracy               0.8675
Name: 3, dtype: object

In [255]:
from sklearn.metrics import classification_report

y_pred = gb.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1593
           1       0.79      0.48      0.59       407

    accuracy                           0.87      2000
   macro avg       0.83      0.72      0.76      2000
weighted avg       0.86      0.87      0.85      2000

In [256]:
joblib.dump(gb, "bank_churn_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(le_country, "country_encoder.pkl")
joblib.dump(le_gender, "gender_encoder.pkl")

['gender_encoder.pkl']