Q1 ]
- Classification Dataset (Heart Disease)

In [1]:
import pandas as pd

# Load Dataset
df_class = pd.read_csv("heart.csv")

# Display Dataset
print(df_class.head())

# Dataset Information
print(df_class.info())

# Check Missing Values
print(df_class.isnull().sum())

# Remove Missing Values
df_class = df_class.dropna()

# Remove Duplicate Rows
df_class = df_class.drop_duplicates()

# Reset Index
df_class.reset_index(drop=True, inplace=True)

# Replace invalid values with mean
columns_to_fix = ["RestingBP", "Cholesterol"]

for col in columns_to_fix:
    mean_value = df_class.loc[df_class[col] != 0, col].mean()
    df_class[col] = df_class[col].replace(0, mean_value)

   Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172
1   49   F           NAP        160          180          0     Normal    156
2   37   M           ATA        130          283          0         ST     98
3   48   F           ASY        138          214          0     Normal    108
4   54   M           NAP        150          195          0     Normal    122

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease
0              N      0.0       Up             0
1              N      1.0     Flat             1
2              N      0.0       Up             0
3              Y      1.5     Flat             1
4              N      0.0       Up             0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB
None
Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [2]:
print("Duplicate Rows :", df_class.duplicated().sum())

print("\nRestingBP Zero Values :", (df_class["RestingBP"] == 0).sum())
print("Cholesterol Zero Values :", (df_class["Cholesterol"] == 0).sum())

Duplicate Rows : 0

RestingBP Zero Values : 0
Cholesterol Zero Values : 0

In [3]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# One-Hot Encoding
df_class_encoded = pd.get_dummies(df_class)

# Independent Features (X)
X_class = df_class_encoded.drop("HeartDisease", axis=1)

# Dependent Feature (y)
y_class = df_class_encoded["HeartDisease"]

In [4]:
# Train-Test Split
X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(
    X_class,
    y_class,
    test_size=0.2,
    random_state=42
)

# Feature Scaling
scaler_class = StandardScaler()

X_train_class = scaler_class.fit_transform(X_train_class)
X_test_class = scaler_class.transform(X_test_class)

print("X Shape :", X_class.shape)
print("y Shape :", y_class.shape)
print("X_train :", X_train_class.shape)
print("X_test  :", X_test_class.shape)

X Shape : (918, 20)
y Shape : (918,)
X_train : (734, 20)
X_test  : (184, 20)

Q1 ]
- Regression Dataset (Car Price)

In [5]:
import pandas as pd

# Load Dataset
df_reg = pd.read_csv("Car_Price_Prediction.csv")

# Display Dataset
print(df_reg.head())

# Dataset Information
df_reg.info()

# Check Missing Values
print(df_reg.isnull().sum())

# Check Duplicate Rows
print("Duplicate Rows :", df_reg.duplicated().sum())

# Remove Missing Values
df_reg.dropna(inplace=True)

# Remove Duplicate Rows
df_reg.drop_duplicates(inplace=True)

# Reset Index
df_reg.reset_index(drop=True, inplace=True)

# Display Cleaned Dataset
df_reg

    Make    Model  Year  Engine Size  Mileage Fuel Type Transmission  \
0  Honda  Model B  2015          3.9    74176    Petrol       Manual
1   Ford  Model C  2014          1.7    94799  Electric    Automatic
2    BMW  Model B  2006          4.1    98385  Electric       Manual
3  Honda  Model B  2015          2.6    88919  Electric    Automatic
4  Honda  Model C  2004          3.4   138482    Petrol    Automatic

          Price
0  30246.207931
1  22785.747684
2  25760.290347
3  25638.003491
4  21021.386657
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Make          1000 non-null   object
 1   Model         1000 non-null   object
 2   Year          1000 non-null   int64
 3   Engine Size   1000 non-null   float64
 4   Mileage       1000 non-null   int64
 5   Fuel Type     1000 non-null   object
 6   Transmission  1000 non-null   object
 7   Price         1000 non-null   float64
dtypes: float64(2), int64(2), object(4)
memory usage: 62.6+ KB
Make            0
Model           0
Year            0
Engine Size     0
Mileage         0
Fuel Type       0
Transmission    0
Price           0
dtype: int64
Duplicate Rows : 0

,Make,Model,Year,Engine Size,Mileage,Fuel Type,Transmission,Price
0,Honda,Model B,2015,3.9,74176,Petrol,Manual,30246.207931
1,Ford,Model C,2014,1.7,94799,Electric,Automatic,22785.747684
2,BMW,Model B,2006,4.1,98385,Electric,Manual,25760.290347
3,Honda,Model B,2015,2.6,88919,Electric,Automatic,25638.003491
4,Honda,Model C,2004,3.4,138482,Petrol,Automatic,21021.386657
...,...,...,...,...,...,...,...,...
995,Toyota,Model D,2002,1.9,5445,Petrol,Manual,22765.597091
996,Honda,Model B,2020,3.1,149112,Diesel,Manual,30392.575567
997,Ford,Model C,2008,1.9,195387,Petrol,Automatic,16446.892292
998,Toyota,Model A,2003,4.4,246,Petrol,Automatic,27396.156708
999,Audi,Model C,2020,2.1,31153,Diesel,Automatic,31620.864907

In [6]:
# One-Hot Encoding
df_reg_encoded = pd.get_dummies(df_reg)

# Independent Features (X)
X_reg = df_reg_encoded.drop("Price", axis=1)

# Dependent Feature (y)
y_reg = df_reg_encoded["Price"]

In [7]:
from sklearn.model_selection import train_test_split


# Train-Test Split

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

print("X Shape :", X_reg.shape)
print("y Shape :", y_reg.shape)
print("X_train :", X_train_reg.shape)
print("X_test  :", X_test_reg.shape)

X Shape : (1000, 18)
y Shape : (1000,)
X_train : (800, 18)
X_test  : (200, 18)

Q 2.1 ]
- (Classification Algorithms)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train Logistic Regression Model
modelLogi = LogisticRegression(max_iter=1000)

modelLogi.fit(X_train_class, y_train_class)

# Prediction
y_pred_Logi = modelLogi.predict(X_test_class)

# Evaluation
accuracy_Logi = accuracy_score(y_test_class, y_pred_Logi)

print("Accuracy :", accuracy_Logi)

print("\nConfusion Matrix")
print(confusion_matrix(y_test_class, y_pred_Logi))

print("\nClassification Report")
print(classification_report(y_test_class, y_pred_Logi))

Accuracy : 0.8641304347826086

Confusion Matrix
[[68  9]
 [16 91]]

Classification Report
              precision    recall  f1-score   support

           0       0.81      0.88      0.84        77
           1       0.91      0.85      0.88       107

    accuracy                           0.86       184
   macro avg       0.86      0.87      0.86       184
weighted avg       0.87      0.86      0.86       184

Q 2.2 ]
-  (Regression Algorithms)

In [9]:
from sklearn.tree import DecisionTreeClassifier

# Train Decision Tree Model
modelDT = DecisionTreeClassifier(random_state=42)

modelDT.fit(X_train_class, y_train_class)

# Prediction
y_pred_DT = modelDT.predict(X_test_class)

# Evaluation
accuracy_DT = accuracy_score(y_test_class, y_pred_DT)

print("Accuracy :", accuracy_DT)

print("\nConfusion Matrix")
print(confusion_matrix(y_test_class, y_pred_DT))

print("\nClassification Report")
print(classification_report(y_test_class, y_pred_DT))

Accuracy : 0.8315217391304348

Confusion Matrix
[[70  7]
 [24 83]]

Classification Report
              precision    recall  f1-score   support

           0       0.74      0.91      0.82        77
           1       0.92      0.78      0.84       107

    accuracy                           0.83       184
   macro avg       0.83      0.84      0.83       184
weighted avg       0.85      0.83      0.83       184

Q 2.3 ]
- Support Vector Machine (SVM)

In [10]:
from sklearn.svm import SVC

# Train SVM Model
modelSVM = SVC()

modelSVM.fit(X_train_class, y_train_class)

# Prediction
y_pred_SVM = modelSVM.predict(X_test_class)

# Evaluation
accuracy_SVM = accuracy_score(y_test_class, y_pred_SVM)

print("Accuracy :", accuracy_SVM)

print("\nConfusion Matrix")
print(confusion_matrix(y_test_class, y_pred_SVM))

print("\nClassification Report")
print(classification_report(y_test_class, y_pred_SVM))

Accuracy : 0.8641304347826086

Confusion Matrix
[[67 10]
 [15 92]]

Classification Report
              precision    recall  f1-score   support

           0       0.82      0.87      0.84        77
           1       0.90      0.86      0.88       107

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.87      0.86      0.86       184

Q 2.4 ]
- K-Nearest Neighbors

In [11]:
from sklearn.neighbors import KNeighborsClassifier

# Train KNN Model
modelKNN = KNeighborsClassifier(n_neighbors=5)

modelKNN.fit(X_train_class, y_train_class)

# Prediction
y_pred_KNN = modelKNN.predict(X_test_class)

# Evaluation
accuracy_KNN = accuracy_score(y_test_class, y_pred_KNN)

print("Accuracy :", accuracy_KNN)

print("\nConfusion Matrix")
print(confusion_matrix(y_test_class, y_pred_KNN))

print("\nClassification Report")
print(classification_report(y_test_class, y_pred_KNN))

Accuracy : 0.8532608695652174

Confusion Matrix
[[67 10]
 [17 90]]

Classification Report
              precision    recall  f1-score   support

           0       0.80      0.87      0.83        77
           1       0.90      0.84      0.87       107

    accuracy                           0.85       184
   macro avg       0.85      0.86      0.85       184
weighted avg       0.86      0.85      0.85       184

Q 2.5 ] 
- Gaussian Naive Bayes

In [12]:
from sklearn.naive_bayes import GaussianNB

# Train Naive Bayes Model
modelNB = GaussianNB()

modelNB.fit(X_train_class, y_train_class)

# Prediction
y_pred_NB = modelNB.predict(X_test_class)

# Evaluation
accuracy_NB = accuracy_score(y_test_class, y_pred_NB)

print("Accuracy :", accuracy_NB)

print("\nConfusion Matrix")
print(confusion_matrix(y_test_class, y_pred_NB))

print("\nClassification Report")
print(classification_report(y_test_class, y_pred_NB))

Accuracy : 0.8369565217391305

Confusion Matrix
[[69  8]
 [22 85]]

Classification Report
              precision    recall  f1-score   support

           0       0.76      0.90      0.82        77
           1       0.91      0.79      0.85       107

    accuracy                           0.84       184
   macro avg       0.84      0.85      0.84       184
weighted avg       0.85      0.84      0.84       184

Q 2.6 ]
- Comparison Table

In [13]:
import pandas as pd

print("-------- Comparison Table ---------")
comparison = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "Decision Tree",
        "Support Vector Machine",
        "K-Nearest Neighbors",
        "Gaussian Naive Bayes"
    ],
    "Accuracy": [
        accuracy_Logi,
        accuracy_DT,
        accuracy_SVM,
        accuracy_KNN,
        accuracy_NB
    ]
})

comparison

-------- Comparison Table ---------

                Algorithm  Accuracy
0     Logistic Regression  0.864130
1           Decision Tree  0.831522
2  Support Vector Machine  0.864130
3     K-Nearest Neighbors  0.853261
4    Gaussian Naive Bayes  0.836957

In [14]:
# sorting Table Accuracy values in decentding order

comparison.sort_values(by="Accuracy", ascending=False)

                Algorithm  Accuracy
0     Logistic Regression  0.864130
2  Support Vector Machine  0.864130
3     K-Nearest Neighbors  0.853261
4    Gaussian Naive Bayes  0.836957
1           Decision Tree  0.831522

Q 3.1 ]
- Linear Regression

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Train Linear Regression Model
modelLR = LinearRegression()

modelLR.fit(X_train_reg, y_train_reg)

# Prediction
y_pred_LR = modelLR.predict(X_test_reg)

# Evaluation
r2_LR = r2_score(y_test_reg, y_pred_LR)

print("R2 Score :", r2_LR)

R2 Score : 0.8170961815663534

Q 3.2 ]
- Decision Tree Regressor

In [16]:
from sklearn.tree import DecisionTreeRegressor

# Train Decision Tree Regressor
modelDTR = DecisionTreeRegressor(random_state=42)

modelDTR.fit(X_train_reg, y_train_reg)

# Prediction
y_pred_DTR = modelDTR.predict(X_test_reg)

# Evaluation
r2_DTR = r2_score(y_test_reg, y_pred_DTR)

print("R2 Score :", r2_DTR)

R2 Score : 0.6286063171432139

Q 3.3 ]
- Support Vector Regressor (SVR)

In [17]:
from sklearn.preprocessing import StandardScaler

# Feature Scaling
scaler_reg = StandardScaler()

X_train_reg_scaled = scaler_reg.fit_transform(X_train_reg)
X_test_reg_scaled = scaler_reg.transform(X_test_reg)

In [18]:
from sklearn.svm import SVR

# Train SVR Model
modelSVR = SVR()

modelSVR.fit(X_train_reg_scaled, y_train_reg)

# Prediction
y_pred_SVR = modelSVR.predict(X_test_reg_scaled)

# Evaluation
r2_SVR = r2_score(y_test_reg, y_pred_SVR)

print("R2 Score :", r2_SVR)

R2 Score : 0.0033600724227490497

Q 3.4 ]
- K-Nearest Neighbors Regressor

In [19]:
from sklearn.neighbors import KNeighborsRegressor

# Train KNN Regressor
modelKNNR = KNeighborsRegressor(n_neighbors=5)

modelKNNR.fit(X_train_reg_scaled, y_train_reg)

# Prediction
y_pred_KNNR = modelKNNR.predict(X_test_reg_scaled)

# Evaluation
r2_KNNR = r2_score(y_test_reg, y_pred_KNNR)

print("R2 Score :", r2_KNNR)

R2 Score : 0.2411134579262112

Q 3.5 ] 
- Comparison Table

In [20]:
comparison_reg = pd.DataFrame({
    "Algorithm": [
        "Linear Regression",
        "Decision Tree Regressor",
        "Support Vector Regressor",
        "K-Nearest Neighbors Regressor"
    ],
    "R2 Score": [
        r2_LR,
        r2_DTR,
        r2_SVR,
        r2_KNNR
    ]
})

comparison_reg.sort_values(by="R2 Score", ascending=False)

                       Algorithm  R2 Score
0              Linear Regression  0.817096
1        Decision Tree Regressor  0.628606
3  K-Nearest Neighbors Regressor  0.241113
2       Support Vector Regressor  0.003360

Q 4 ]
- Best Model Selection & Saving

In [21]:
import joblib

joblib.dump(modelLogi, "best_class_model.pkl")
joblib.dump(scaler_class, "class_scaler.pkl")
joblib.dump(X_class.columns.tolist(), "class_columns.pkl")


joblib.dump(modelLR, "best_regi_model.pkl")
joblib.dump(scaler_reg, "regi_scaler.pkl")
joblib.dump(X_reg.columns.tolist(), "regi_columns.pkl")


print("\nAll models are saved successfully")


print("best_class_model.pkl")
print("class_scaler.pkl")
print("class_columns.pkl")
print("best_regi_model.pkl")
print("regi_scaler.pkl")
print("regi_columns.pkl")

All models are saved successfully
best_class_model.pkl
class_scaler.pkl
class_columns.pkl
best_regi_model.pkl
regi_scaler.pkl
regi_columns.pkl

In [22]:
# Save Remaining Classification Models
joblib.dump(modelDT, "modelDT.pkl")
joblib.dump(modelSVM, "modelSVM.pkl")
joblib.dump(modelKNN, "modelKNN.pkl")
joblib.dump(modelNB, "modelNB.pkl")

# Save Remaining Regression Models
joblib.dump(modelDTR, "modelDTR.pkl")
joblib.dump(modelSVR, "modelSVR.pkl")
joblib.dump(modelKNNR, "modelKNNR.pkl")

print("\nother Remaining models saved successfully")

print("modelDT.pkl")
print("modelSVM.pkl")
print("modelKNN.pkl")
print("modelNB.pkl")
print("modelDTR.pkl")
print("modelSVR.pkl")
print("modelKNNR.pkl")

other Remaining models saved successfully
modelDT.pkl
modelSVM.pkl
modelKNN.pkl
modelNB.pkl
modelDTR.pkl
modelSVR.pkl
modelKNNR.pkl